# See Bitbucket pipelines for more info
# Used for Automatic testing
image: python:3.7.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        script: 
          - apt update
          - /bin/bash install_dependencies.sh
          - /bin/bash run_tests.sh
