# See Bitbucket pipelines for more info
# Used for Automatic testing of new commits to development and master branches
image: python:3.7.3

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          caches:
            - pip
          script: 
            - apt update
            - /bin/bash install_dependencies.sh
            - /bin/bash run_tests.sh
    development:
      - step:
          name: Build and Test
          caches:
            - pip
          script: 
            - apt update
            - /bin/bash install_dependencies.sh
            - /bin/bash run_tests.sh
