# See Bitbucket pipelines for more info
# Used for Automatic testing
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: 
          - echo "Installing Dependencies"
          - apt update
          - /bin/bash install_dependencies.sh
          - echo "Running Test Scripts"
          - /bin/bash run_tests.sh
