# See Bitbucket pipelines for more info
# Used for Automatic testing of new commits to development and master branches
image: python:3.7.3

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - pip
        script: 
          - apt update
          - /bin/bash install_dependencies.sh -p
          - /bin/bash run_tests.sh

pipelines:
  pull-requests:
    '**':
      - step: *build-test
  branches:
    master:
      - step: *build-test
    development:
      - step: *build-test
          
