# See Bitbucket pipelines for more info
# Used for Automatic testing
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: 
          - echo "Installing Dependencies"
          - /bin/bash install_dependencies.sh
          - echo "Running Test Scripts"
          - source env/venv3/bin/activate
          - cd station && python3 test.py

