# See Bitbucket pipelines for more info
# Used for Automatic testing of new commits to development and master branches
image: python:3.8

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - pip
          - venv
        script: 
          - apt update
          - apt install -y libgl1-mesa-dev # Fix libGl error in docker. https://codeslake.github.io/ubuntu/docker/docker-libGL-error/
          - /bin/bash install_dependencies.sh -p
          - /bin/bash run_tests.sh

pipelines:
  pull-requests:
    '**':
      - step: *build-test
  branches:
    master:
      - step: *build-test
    development:
      - step: *build-test
          
definitions:
  caches:
    # Virtual environment for python
    venv: venv3